// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZpVBOTE-d8qeXdg5048YhetG5jGl3RY',
    appId: '1:1015478328608:web:b6cb45',
    messagingSenderId: '1015478328608',
    projectId: 'fruits-market-ea9fb',
    authDomain: 'fruits-market-ea9fb.firebaseapp.com',
    storageBucket: 'fruits-market-ea9fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZpVBOTE-d8qeXdg5048YhetG5jGl3RY',
    appId: '1:1015478328608:android:1749e6a3d2be5fb4b6cb45',
    messagingSenderId: '1015478328608',
    projectId: 'fruits-market-ea9fb',
    storageBucket: 'fruits-market-ea9fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhZpVBOTE-d8qeXdg5048YhetG5jGl3RY',
    appId: '1:1015478328608:ios:b6cb45',
    messagingSenderId: '1015478328608',
    projectId: 'fruits-market-ea9fb',
    storageBucket: 'fruits-market-ea9fb.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhZpVBOTE-d8qeXdg5048YhetG5jGl3RY',
    appId: '1:1015478328608:ios:b6cb45',
    messagingSenderId: '1015478328608',
    projectId: 'fruits-market-ea9fb',
    storageBucket: 'fruits-market-ea9fb.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhZpVBOTE-d8qeXdg5048YhetG5jGl3RY',
    appId: '1:1015478328608:web:b6cb45',
    messagingSenderId: '1015478328608',
    projectId: 'fruits-market-ea9fb',
    authDomain: 'fruits-market-ea9fb.firebaseapp.com',
    storageBucket: 'fruits-market-ea9fb.firebasestorage.app',
  );
}
